namespace FastFoodDemo
{
    partial class StaffAdd
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(StaffAdd));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.HeaderLabel = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.ButtonCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AddButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.DatePicker = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.PositionLabel = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.HiringStatusLabel = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.EmailField = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.EmailLabel = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.PassportField = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.PassportLabel = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.AdressField = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.MobPhoneField = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.MiddlenameField = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.NameField = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.SurnameField = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.DateOfEmploymentLabel = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.MobPhoneLabel = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.AdressLabel = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.MiddlenameLabel = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.NameLabel = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.SurnameLabel = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.PositionDropdown = new Bunifu.UI.WinForms.BunifuDropdown();
            this.HiringStatusDropdown = new Bunifu.UI.WinForms.BunifuDropdown();
            this.SuspendLayout();
            // 
            // HeaderLabel
            // 
            this.HeaderLabel.AutoSize = true;
            this.HeaderLabel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(8)))), ((int)(((byte)(55)))));
            this.HeaderLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.HeaderLabel.Font = new System.Drawing.Font("Century Gothic", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.HeaderLabel.ForeColor = System.Drawing.Color.White;
            this.HeaderLabel.Location = new System.Drawing.Point(0, 0);
            this.HeaderLabel.MaximumSize = new System.Drawing.Size(285, 35);
            this.HeaderLabel.MinimumSize = new System.Drawing.Size(315, 35);
            this.HeaderLabel.Name = "HeaderLabel";
            this.HeaderLabel.Size = new System.Drawing.Size(315, 35);
            this.HeaderLabel.TabIndex = 1;
            this.HeaderLabel.Text = "Добавление сотрудника";
            this.HeaderLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // ButtonCancel
            // 
            this.ButtonCancel.AllowAnimations = true;
            this.ButtonCancel.AllowMouseEffects = true;
            this.ButtonCancel.AllowToggling = false;
            this.ButtonCancel.AnimationSpeed = 200;
            this.ButtonCancel.AutoGenerateColors = true;
            this.ButtonCancel.AutoRoundBorders = false;
            this.ButtonCancel.AutoSizeLeftIcon = true;
            this.ButtonCancel.AutoSizeRightIcon = true;
            this.ButtonCancel.BackColor = System.Drawing.Color.Transparent;
            this.ButtonCancel.BackColor1 = System.Drawing.Color.Black;
            this.ButtonCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ButtonCancel.BackgroundImage")));
            this.ButtonCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonCancel.ButtonText = "Отмена";
            this.ButtonCancel.ButtonTextMarginLeft = 0;
            this.ButtonCancel.ColorContrastOnClick = 45;
            this.ButtonCancel.ColorContrastOnHover = 90;
            this.ButtonCancel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.ButtonCancel.CustomizableEdges = borderEdges1;
            this.ButtonCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ButtonCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.ButtonCancel.DisabledFillColor = System.Drawing.Color.Gray;
            this.ButtonCancel.DisabledForecolor = System.Drawing.Color.White;
            this.ButtonCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ButtonCancel.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ButtonCancel.ForeColor = System.Drawing.Color.White;
            this.ButtonCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ButtonCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ButtonCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ButtonCancel.IconMarginLeft = 11;
            this.ButtonCancel.IconPadding = 10;
            this.ButtonCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ButtonCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ButtonCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ButtonCancel.IconSize = 25;
            this.ButtonCancel.IdleBorderColor = System.Drawing.Color.Black;
            this.ButtonCancel.IdleBorderRadius = 1;
            this.ButtonCancel.IdleBorderThickness = 1;
            this.ButtonCancel.IdleFillColor = System.Drawing.Color.Black;
            this.ButtonCancel.IdleIconLeftImage = null;
            this.ButtonCancel.IdleIconRightImage = null;
            this.ButtonCancel.IndicateFocus = true;
            this.ButtonCancel.Location = new System.Drawing.Point(100, 400);
            this.ButtonCancel.Name = "ButtonCancel";
            this.ButtonCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.ButtonCancel.OnDisabledState.BorderRadius = 1;
            this.ButtonCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonCancel.OnDisabledState.BorderThickness = 1;
            this.ButtonCancel.OnDisabledState.FillColor = System.Drawing.Color.Gray;
            this.ButtonCancel.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.ButtonCancel.OnDisabledState.IconLeftImage = null;
            this.ButtonCancel.OnDisabledState.IconRightImage = null;
            this.ButtonCancel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(229)))), ((int)(((byte)(229)))));
            this.ButtonCancel.onHoverState.BorderRadius = 1;
            this.ButtonCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonCancel.onHoverState.BorderThickness = 1;
            this.ButtonCancel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(229)))), ((int)(((byte)(229)))));
            this.ButtonCancel.onHoverState.ForeColor = System.Drawing.Color.Empty;
            this.ButtonCancel.onHoverState.IconLeftImage = null;
            this.ButtonCancel.onHoverState.IconRightImage = null;
            this.ButtonCancel.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.ButtonCancel.OnIdleState.BorderRadius = 1;
            this.ButtonCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonCancel.OnIdleState.BorderThickness = 1;
            this.ButtonCancel.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.ButtonCancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ButtonCancel.OnIdleState.IconLeftImage = null;
            this.ButtonCancel.OnIdleState.IconRightImage = null;
            this.ButtonCancel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.ButtonCancel.OnPressedState.BorderRadius = 1;
            this.ButtonCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonCancel.OnPressedState.BorderThickness = 1;
            this.ButtonCancel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.ButtonCancel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ButtonCancel.OnPressedState.IconLeftImage = null;
            this.ButtonCancel.OnPressedState.IconRightImage = null;
            this.ButtonCancel.Size = new System.Drawing.Size(104, 45);
            this.ButtonCancel.TabIndex = 73;
            this.ButtonCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ButtonCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ButtonCancel.TextMarginLeft = 0;
            this.ButtonCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.ButtonCancel.UseDefaultRadiusAndThickness = true;
            this.ButtonCancel.Click += new System.EventHandler(this.ButtonCancel_Click);
            // 
            // AddButton
            // 
            this.AddButton.AllowAnimations = true;
            this.AddButton.AllowMouseEffects = true;
            this.AddButton.AllowToggling = false;
            this.AddButton.AnimationSpeed = 200;
            this.AddButton.AutoGenerateColors = true;
            this.AddButton.AutoRoundBorders = false;
            this.AddButton.AutoSizeLeftIcon = true;
            this.AddButton.AutoSizeRightIcon = true;
            this.AddButton.BackColor = System.Drawing.Color.Transparent;
            this.AddButton.BackColor1 = System.Drawing.Color.Firebrick;
            this.AddButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AddButton.BackgroundImage")));
            this.AddButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddButton.ButtonText = "Добавить";
            this.AddButton.ButtonTextMarginLeft = 0;
            this.AddButton.ColorContrastOnClick = 45;
            this.AddButton.ColorContrastOnHover = 91;
            this.AddButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.AddButton.CustomizableEdges = borderEdges2;
            this.AddButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AddButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.AddButton.DisabledFillColor = System.Drawing.Color.Gray;
            this.AddButton.DisabledForecolor = System.Drawing.Color.White;
            this.AddButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AddButton.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.AddButton.ForeColor = System.Drawing.Color.White;
            this.AddButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AddButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AddButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AddButton.IconMarginLeft = 11;
            this.AddButton.IconPadding = 10;
            this.AddButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AddButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AddButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AddButton.IconSize = 25;
            this.AddButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            this.AddButton.IdleBorderRadius = 1;
            this.AddButton.IdleBorderThickness = 1;
            this.AddButton.IdleFillColor = System.Drawing.Color.Firebrick;
            this.AddButton.IdleIconLeftImage = null;
            this.AddButton.IdleIconRightImage = null;
            this.AddButton.IndicateFocus = true;
            this.AddButton.Location = new System.Drawing.Point(203, 400);
            this.AddButton.Name = "AddButton";
            this.AddButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.AddButton.OnDisabledState.BorderRadius = 1;
            this.AddButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddButton.OnDisabledState.BorderThickness = 1;
            this.AddButton.OnDisabledState.FillColor = System.Drawing.Color.Gray;
            this.AddButton.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.AddButton.OnDisabledState.IconLeftImage = null;
            this.AddButton.OnDisabledState.IconRightImage = null;
            this.AddButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.AddButton.onHoverState.BorderRadius = 1;
            this.AddButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddButton.onHoverState.BorderThickness = 1;
            this.AddButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(235)))), ((int)(((byte)(235)))));
            this.AddButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.AddButton.onHoverState.IconLeftImage = null;
            this.AddButton.onHoverState.IconRightImage = null;
            this.AddButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            this.AddButton.OnIdleState.BorderRadius = 1;
            this.AddButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddButton.OnIdleState.BorderThickness = 1;
            this.AddButton.OnIdleState.FillColor = System.Drawing.Color.Firebrick;
            this.AddButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AddButton.OnIdleState.IconLeftImage = null;
            this.AddButton.OnIdleState.IconRightImage = null;
            this.AddButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(62)))), ((int)(((byte)(62)))), ((int)(((byte)(62)))));
            this.AddButton.OnPressedState.BorderRadius = 1;
            this.AddButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddButton.OnPressedState.BorderThickness = 1;
            this.AddButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(97)))), ((int)(((byte)(18)))), ((int)(((byte)(18)))));
            this.AddButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AddButton.OnPressedState.IconLeftImage = null;
            this.AddButton.OnPressedState.IconRightImage = null;
            this.AddButton.Size = new System.Drawing.Size(104, 45);
            this.AddButton.TabIndex = 72;
            this.AddButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AddButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AddButton.TextMarginLeft = 0;
            this.AddButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.AddButton.UseDefaultRadiusAndThickness = true;
            this.AddButton.Click += new System.EventHandler(this.AddButton_Click);
            // 
            // DatePicker
            // 
            this.DatePicker.BackColor = System.Drawing.Color.Transparent;
            this.DatePicker.BorderRadius = 2;
            this.DatePicker.CalendarFont = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.DatePicker.CalendarTrailingForeColor = System.Drawing.Color.White;
            this.DatePicker.Color = System.Drawing.Color.Black;
            this.DatePicker.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thick;
            this.DatePicker.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.DatePicker.DisabledColor = System.Drawing.Color.Black;
            this.DatePicker.DisplayWeekNumbers = false;
            this.DatePicker.DPHeight = 0;
            this.DatePicker.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.DatePicker.FillDatePicker = false;
            this.DatePicker.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.DatePicker.ForeColor = System.Drawing.Color.Black;
            this.DatePicker.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.DatePicker.Icon = ((System.Drawing.Image)(resources.GetObject("DatePicker.Icon")));
            this.DatePicker.IconColor = System.Drawing.Color.Transparent;
            this.DatePicker.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.DatePicker.LeftTextMargin = 5;
            this.DatePicker.Location = new System.Drawing.Point(100, 139);
            this.DatePicker.MinimumSize = new System.Drawing.Size(208, 35);
            this.DatePicker.Name = "DatePicker";
            this.DatePicker.Size = new System.Drawing.Size(208, 35);
            this.DatePicker.TabIndex = 83;
            // 
            // PositionLabel
            // 
            this.PositionLabel.AutoSize = true;
            this.PositionLabel.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.PositionLabel.Location = new System.Drawing.Point(2, 363);
            this.PositionLabel.Name = "PositionLabel";
            this.PositionLabel.Size = new System.Drawing.Size(98, 19);
            this.PositionLabel.TabIndex = 92;
            this.PositionLabel.Text = "Должность";
            // 
            // HiringStatusLabel
            // 
            this.HiringStatusLabel.AutoSize = true;
            this.HiringStatusLabel.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.HiringStatusLabel.Location = new System.Drawing.Point(2, 309);
            this.HiringStatusLabel.Name = "HiringStatusLabel";
            this.HiringStatusLabel.Size = new System.Drawing.Size(71, 38);
            this.HiringStatusLabel.TabIndex = 90;
            this.HiringStatusLabel.Text = "Статус \r\nнайма";
            // 
            // EmailField
            // 
            this.EmailField.AcceptsReturn = false;
            this.EmailField.AcceptsTab = false;
            this.EmailField.AnimationSpeed = 200;
            this.EmailField.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.EmailField.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.EmailField.BackColor = System.Drawing.Color.Transparent;
            this.EmailField.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("EmailField.BackgroundImage")));
            this.EmailField.BorderColorActive = System.Drawing.Color.Black;
            this.EmailField.BorderColorDisabled = System.Drawing.Color.Black;
            this.EmailField.BorderColorHover = System.Drawing.Color.Black;
            this.EmailField.BorderColorIdle = System.Drawing.Color.Black;
            this.EmailField.BorderRadius = 1;
            this.EmailField.BorderThickness = 2;
            this.EmailField.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.EmailField.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.EmailField.DefaultFont = new System.Drawing.Font("Century Gothic", 11.25F);
            this.EmailField.DefaultText = "";
            this.EmailField.FillColor = System.Drawing.Color.White;
            this.EmailField.ForeColor = System.Drawing.SystemColors.ControlText;
            this.EmailField.HideSelection = true;
            this.EmailField.IconLeft = null;
            this.EmailField.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.EmailField.IconPadding = 10;
            this.EmailField.IconRight = null;
            this.EmailField.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.EmailField.Lines = new string[0];
            this.EmailField.Location = new System.Drawing.Point(98, 276);
            this.EmailField.MaxLength = 32767;
            this.EmailField.MinimumSize = new System.Drawing.Size(100, 35);
            this.EmailField.Modified = false;
            this.EmailField.Multiline = false;
            this.EmailField.Name = "EmailField";
            stateProperties1.BorderColor = System.Drawing.Color.Black;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmailField.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Black;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.EmailField.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Black;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmailField.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Black;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.SystemColors.ControlText;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmailField.OnIdleState = stateProperties4;
            this.EmailField.PasswordChar = '\0';
            this.EmailField.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.EmailField.PlaceholderText = "";
            this.EmailField.ReadOnly = false;
            this.EmailField.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.EmailField.SelectedText = "";
            this.EmailField.SelectionLength = 0;
            this.EmailField.SelectionStart = 0;
            this.EmailField.ShortcutsEnabled = true;
            this.EmailField.Size = new System.Drawing.Size(210, 35);
            this.EmailField.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.EmailField.TabIndex = 87;
            this.EmailField.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.EmailField.TextMarginBottom = 0;
            this.EmailField.TextMarginLeft = 5;
            this.EmailField.TextMarginTop = 0;
            this.EmailField.TextPlaceholder = "";
            this.EmailField.UseSystemPasswordChar = false;
            this.EmailField.WordWrap = true;
            // 
            // EmailLabel
            // 
            this.EmailLabel.AutoSize = true;
            this.EmailLabel.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.EmailLabel.Location = new System.Drawing.Point(2, 283);
            this.EmailLabel.Name = "EmailLabel";
            this.EmailLabel.Size = new System.Drawing.Size(87, 19);
            this.EmailLabel.TabIndex = 88;
            this.EmailLabel.Text = "Эл. Почта";
            // 
            // PassportField
            // 
            this.PassportField.AcceptsReturn = false;
            this.PassportField.AcceptsTab = false;
            this.PassportField.AnimationSpeed = 200;
            this.PassportField.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PassportField.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PassportField.BackColor = System.Drawing.Color.Transparent;
            this.PassportField.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PassportField.BackgroundImage")));
            this.PassportField.BorderColorActive = System.Drawing.Color.Black;
            this.PassportField.BorderColorDisabled = System.Drawing.Color.Black;
            this.PassportField.BorderColorHover = System.Drawing.Color.Black;
            this.PassportField.BorderColorIdle = System.Drawing.Color.Black;
            this.PassportField.BorderRadius = 1;
            this.PassportField.BorderThickness = 2;
            this.PassportField.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PassportField.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PassportField.DefaultFont = new System.Drawing.Font("Century Gothic", 11.25F);
            this.PassportField.DefaultText = "";
            this.PassportField.FillColor = System.Drawing.Color.White;
            this.PassportField.ForeColor = System.Drawing.SystemColors.ControlText;
            this.PassportField.HideSelection = true;
            this.PassportField.IconLeft = null;
            this.PassportField.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.PassportField.IconPadding = 10;
            this.PassportField.IconRight = null;
            this.PassportField.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.PassportField.Lines = new string[0];
            this.PassportField.Location = new System.Drawing.Point(99, 242);
            this.PassportField.MaxLength = 32767;
            this.PassportField.MinimumSize = new System.Drawing.Size(100, 35);
            this.PassportField.Modified = false;
            this.PassportField.Multiline = false;
            this.PassportField.Name = "PassportField";
            stateProperties5.BorderColor = System.Drawing.Color.Black;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PassportField.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Black;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.PassportField.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Black;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PassportField.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Black;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.SystemColors.ControlText;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PassportField.OnIdleState = stateProperties8;
            this.PassportField.PasswordChar = '\0';
            this.PassportField.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.PassportField.PlaceholderText = "";
            this.PassportField.ReadOnly = false;
            this.PassportField.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PassportField.SelectedText = "";
            this.PassportField.SelectionLength = 0;
            this.PassportField.SelectionStart = 0;
            this.PassportField.ShortcutsEnabled = true;
            this.PassportField.Size = new System.Drawing.Size(209, 35);
            this.PassportField.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.PassportField.TabIndex = 86;
            this.PassportField.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PassportField.TextMarginBottom = 0;
            this.PassportField.TextMarginLeft = 5;
            this.PassportField.TextMarginTop = 0;
            this.PassportField.TextPlaceholder = "";
            this.PassportField.UseSystemPasswordChar = false;
            this.PassportField.WordWrap = true;
            this.PassportField.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.BunifuTextBox6_KeyPress);
            // 
            // PassportLabel
            // 
            this.PassportLabel.AutoSize = true;
            this.PassportLabel.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.PassportLabel.Location = new System.Drawing.Point(2, 249);
            this.PassportLabel.Name = "PassportLabel";
            this.PassportLabel.Size = new System.Drawing.Size(80, 19);
            this.PassportLabel.TabIndex = 86;
            this.PassportLabel.Text = "Паспорт";
            // 
            // AdressField
            // 
            this.AdressField.AcceptsReturn = false;
            this.AdressField.AcceptsTab = false;
            this.AdressField.AnimationSpeed = 200;
            this.AdressField.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdressField.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdressField.BackColor = System.Drawing.Color.Transparent;
            this.AdressField.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdressField.BackgroundImage")));
            this.AdressField.BorderColorActive = System.Drawing.Color.Black;
            this.AdressField.BorderColorDisabled = System.Drawing.Color.Black;
            this.AdressField.BorderColorHover = System.Drawing.Color.Black;
            this.AdressField.BorderColorIdle = System.Drawing.Color.Black;
            this.AdressField.BorderRadius = 1;
            this.AdressField.BorderThickness = 2;
            this.AdressField.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdressField.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdressField.DefaultFont = new System.Drawing.Font("Century Gothic", 11.25F);
            this.AdressField.DefaultText = "";
            this.AdressField.FillColor = System.Drawing.Color.White;
            this.AdressField.ForeColor = System.Drawing.SystemColors.ControlText;
            this.AdressField.HideSelection = true;
            this.AdressField.IconLeft = null;
            this.AdressField.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdressField.IconPadding = 10;
            this.AdressField.IconRight = null;
            this.AdressField.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdressField.Lines = new string[0];
            this.AdressField.Location = new System.Drawing.Point(99, 174);
            this.AdressField.MaxLength = 32767;
            this.AdressField.MinimumSize = new System.Drawing.Size(100, 35);
            this.AdressField.Modified = false;
            this.AdressField.Multiline = false;
            this.AdressField.Name = "AdressField";
            stateProperties9.BorderColor = System.Drawing.Color.Black;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdressField.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Black;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdressField.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Black;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdressField.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Black;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.SystemColors.ControlText;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdressField.OnIdleState = stateProperties12;
            this.AdressField.PasswordChar = '\0';
            this.AdressField.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdressField.PlaceholderText = "";
            this.AdressField.ReadOnly = false;
            this.AdressField.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdressField.SelectedText = "";
            this.AdressField.SelectionLength = 0;
            this.AdressField.SelectionStart = 0;
            this.AdressField.ShortcutsEnabled = true;
            this.AdressField.Size = new System.Drawing.Size(209, 35);
            this.AdressField.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.AdressField.TabIndex = 84;
            this.AdressField.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdressField.TextMarginBottom = 0;
            this.AdressField.TextMarginLeft = 5;
            this.AdressField.TextMarginTop = 0;
            this.AdressField.TextPlaceholder = "";
            this.AdressField.UseSystemPasswordChar = false;
            this.AdressField.WordWrap = true;
            // 
            // MobPhoneField
            // 
            this.MobPhoneField.AcceptsReturn = false;
            this.MobPhoneField.AcceptsTab = false;
            this.MobPhoneField.AnimationSpeed = 200;
            this.MobPhoneField.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.MobPhoneField.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.MobPhoneField.BackColor = System.Drawing.Color.Transparent;
            this.MobPhoneField.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("MobPhoneField.BackgroundImage")));
            this.MobPhoneField.BorderColorActive = System.Drawing.Color.Black;
            this.MobPhoneField.BorderColorDisabled = System.Drawing.Color.Black;
            this.MobPhoneField.BorderColorHover = System.Drawing.Color.Black;
            this.MobPhoneField.BorderColorIdle = System.Drawing.Color.Black;
            this.MobPhoneField.BorderRadius = 1;
            this.MobPhoneField.BorderThickness = 2;
            this.MobPhoneField.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.MobPhoneField.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.MobPhoneField.DefaultFont = new System.Drawing.Font("Century Gothic", 11.25F);
            this.MobPhoneField.DefaultText = "";
            this.MobPhoneField.FillColor = System.Drawing.Color.White;
            this.MobPhoneField.ForeColor = System.Drawing.SystemColors.ControlText;
            this.MobPhoneField.HideSelection = true;
            this.MobPhoneField.IconLeft = null;
            this.MobPhoneField.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.MobPhoneField.IconPadding = 10;
            this.MobPhoneField.IconRight = null;
            this.MobPhoneField.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.MobPhoneField.Lines = new string[0];
            this.MobPhoneField.Location = new System.Drawing.Point(99, 208);
            this.MobPhoneField.MaxLength = 32767;
            this.MobPhoneField.MinimumSize = new System.Drawing.Size(100, 35);
            this.MobPhoneField.Modified = false;
            this.MobPhoneField.Multiline = false;
            this.MobPhoneField.Name = "MobPhoneField";
            stateProperties13.BorderColor = System.Drawing.Color.Black;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MobPhoneField.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Black;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.MobPhoneField.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Black;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MobPhoneField.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Black;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.SystemColors.ControlText;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MobPhoneField.OnIdleState = stateProperties16;
            this.MobPhoneField.PasswordChar = '\0';
            this.MobPhoneField.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.MobPhoneField.PlaceholderText = "";
            this.MobPhoneField.ReadOnly = false;
            this.MobPhoneField.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.MobPhoneField.SelectedText = "";
            this.MobPhoneField.SelectionLength = 0;
            this.MobPhoneField.SelectionStart = 0;
            this.MobPhoneField.ShortcutsEnabled = true;
            this.MobPhoneField.Size = new System.Drawing.Size(209, 35);
            this.MobPhoneField.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.MobPhoneField.TabIndex = 85;
            this.MobPhoneField.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.MobPhoneField.TextMarginBottom = 0;
            this.MobPhoneField.TextMarginLeft = 5;
            this.MobPhoneField.TextMarginTop = 0;
            this.MobPhoneField.TextPlaceholder = "";
            this.MobPhoneField.UseSystemPasswordChar = false;
            this.MobPhoneField.WordWrap = true;
            this.MobPhoneField.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.BunifuTextBox5_KeyPress);
            // 
            // MiddlenameField
            // 
            this.MiddlenameField.AcceptsReturn = false;
            this.MiddlenameField.AcceptsTab = false;
            this.MiddlenameField.AnimationSpeed = 200;
            this.MiddlenameField.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.MiddlenameField.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.MiddlenameField.BackColor = System.Drawing.Color.Transparent;
            this.MiddlenameField.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("MiddlenameField.BackgroundImage")));
            this.MiddlenameField.BorderColorActive = System.Drawing.Color.Black;
            this.MiddlenameField.BorderColorDisabled = System.Drawing.Color.Black;
            this.MiddlenameField.BorderColorHover = System.Drawing.Color.Black;
            this.MiddlenameField.BorderColorIdle = System.Drawing.Color.Black;
            this.MiddlenameField.BorderRadius = 1;
            this.MiddlenameField.BorderThickness = 2;
            this.MiddlenameField.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.MiddlenameField.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.MiddlenameField.DefaultFont = new System.Drawing.Font("Century Gothic", 11.25F);
            this.MiddlenameField.DefaultText = "";
            this.MiddlenameField.FillColor = System.Drawing.Color.White;
            this.MiddlenameField.ForeColor = System.Drawing.SystemColors.ControlText;
            this.MiddlenameField.HideSelection = true;
            this.MiddlenameField.IconLeft = null;
            this.MiddlenameField.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.MiddlenameField.IconPadding = 10;
            this.MiddlenameField.IconRight = null;
            this.MiddlenameField.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.MiddlenameField.Lines = new string[0];
            this.MiddlenameField.Location = new System.Drawing.Point(99, 104);
            this.MiddlenameField.MaxLength = 32767;
            this.MiddlenameField.MinimumSize = new System.Drawing.Size(100, 35);
            this.MiddlenameField.Modified = false;
            this.MiddlenameField.Multiline = false;
            this.MiddlenameField.Name = "MiddlenameField";
            stateProperties17.BorderColor = System.Drawing.Color.Black;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MiddlenameField.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Black;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.MiddlenameField.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Black;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MiddlenameField.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Black;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.SystemColors.ControlText;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MiddlenameField.OnIdleState = stateProperties20;
            this.MiddlenameField.PasswordChar = '\0';
            this.MiddlenameField.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.MiddlenameField.PlaceholderText = "";
            this.MiddlenameField.ReadOnly = false;
            this.MiddlenameField.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.MiddlenameField.SelectedText = "";
            this.MiddlenameField.SelectionLength = 0;
            this.MiddlenameField.SelectionStart = 0;
            this.MiddlenameField.ShortcutsEnabled = true;
            this.MiddlenameField.Size = new System.Drawing.Size(209, 35);
            this.MiddlenameField.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.MiddlenameField.TabIndex = 82;
            this.MiddlenameField.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.MiddlenameField.TextMarginBottom = 0;
            this.MiddlenameField.TextMarginLeft = 5;
            this.MiddlenameField.TextMarginTop = 0;
            this.MiddlenameField.TextPlaceholder = "";
            this.MiddlenameField.UseSystemPasswordChar = false;
            this.MiddlenameField.WordWrap = true;
            // 
            // NameField
            // 
            this.NameField.AcceptsReturn = false;
            this.NameField.AcceptsTab = false;
            this.NameField.AnimationSpeed = 200;
            this.NameField.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.NameField.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.NameField.BackColor = System.Drawing.Color.Transparent;
            this.NameField.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NameField.BackgroundImage")));
            this.NameField.BorderColorActive = System.Drawing.Color.Black;
            this.NameField.BorderColorDisabled = System.Drawing.Color.Black;
            this.NameField.BorderColorHover = System.Drawing.Color.Black;
            this.NameField.BorderColorIdle = System.Drawing.Color.Black;
            this.NameField.BorderRadius = 1;
            this.NameField.BorderThickness = 2;
            this.NameField.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.NameField.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.NameField.DefaultFont = new System.Drawing.Font("Century Gothic", 11.25F);
            this.NameField.DefaultText = "";
            this.NameField.FillColor = System.Drawing.Color.White;
            this.NameField.ForeColor = System.Drawing.SystemColors.ControlText;
            this.NameField.HideSelection = true;
            this.NameField.IconLeft = null;
            this.NameField.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.NameField.IconPadding = 10;
            this.NameField.IconRight = null;
            this.NameField.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.NameField.Lines = new string[0];
            this.NameField.Location = new System.Drawing.Point(99, 70);
            this.NameField.MaxLength = 32767;
            this.NameField.MinimumSize = new System.Drawing.Size(100, 35);
            this.NameField.Modified = false;
            this.NameField.Multiline = false;
            this.NameField.Name = "NameField";
            stateProperties21.BorderColor = System.Drawing.Color.Black;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NameField.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Black;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.Empty;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.NameField.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.Black;
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NameField.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Black;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.SystemColors.ControlText;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NameField.OnIdleState = stateProperties24;
            this.NameField.PasswordChar = '\0';
            this.NameField.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.NameField.PlaceholderText = "";
            this.NameField.ReadOnly = false;
            this.NameField.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.NameField.SelectedText = "";
            this.NameField.SelectionLength = 0;
            this.NameField.SelectionStart = 0;
            this.NameField.ShortcutsEnabled = true;
            this.NameField.Size = new System.Drawing.Size(209, 35);
            this.NameField.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.NameField.TabIndex = 81;
            this.NameField.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.NameField.TextMarginBottom = 0;
            this.NameField.TextMarginLeft = 5;
            this.NameField.TextMarginTop = 0;
            this.NameField.TextPlaceholder = "";
            this.NameField.UseSystemPasswordChar = false;
            this.NameField.WordWrap = true;
            // 
            // SurnameField
            // 
            this.SurnameField.AcceptsReturn = false;
            this.SurnameField.AcceptsTab = false;
            this.SurnameField.AnimationSpeed = 200;
            this.SurnameField.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.SurnameField.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.SurnameField.BackColor = System.Drawing.Color.Transparent;
            this.SurnameField.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SurnameField.BackgroundImage")));
            this.SurnameField.BorderColorActive = System.Drawing.Color.Black;
            this.SurnameField.BorderColorDisabled = System.Drawing.Color.Black;
            this.SurnameField.BorderColorHover = System.Drawing.Color.Black;
            this.SurnameField.BorderColorIdle = System.Drawing.Color.Black;
            this.SurnameField.BorderRadius = 1;
            this.SurnameField.BorderThickness = 2;
            this.SurnameField.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.SurnameField.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.SurnameField.DefaultFont = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.SurnameField.DefaultText = "";
            this.SurnameField.FillColor = System.Drawing.Color.White;
            this.SurnameField.ForeColor = System.Drawing.SystemColors.ControlText;
            this.SurnameField.HideSelection = true;
            this.SurnameField.IconLeft = null;
            this.SurnameField.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.SurnameField.IconPadding = 10;
            this.SurnameField.IconRight = null;
            this.SurnameField.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.SurnameField.Lines = new string[0];
            this.SurnameField.Location = new System.Drawing.Point(99, 36);
            this.SurnameField.MaxLength = 32767;
            this.SurnameField.MinimumSize = new System.Drawing.Size(100, 35);
            this.SurnameField.Modified = false;
            this.SurnameField.Multiline = false;
            this.SurnameField.Name = "SurnameField";
            stateProperties25.BorderColor = System.Drawing.Color.Black;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SurnameField.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Black;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.Empty;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.SurnameField.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.Black;
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SurnameField.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Black;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.SystemColors.ControlText;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SurnameField.OnIdleState = stateProperties28;
            this.SurnameField.PasswordChar = '\0';
            this.SurnameField.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.SurnameField.PlaceholderText = "";
            this.SurnameField.ReadOnly = false;
            this.SurnameField.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.SurnameField.SelectedText = "";
            this.SurnameField.SelectionLength = 0;
            this.SurnameField.SelectionStart = 0;
            this.SurnameField.ShortcutsEnabled = true;
            this.SurnameField.Size = new System.Drawing.Size(209, 35);
            this.SurnameField.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.SurnameField.TabIndex = 80;
            this.SurnameField.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.SurnameField.TextMarginBottom = 0;
            this.SurnameField.TextMarginLeft = 5;
            this.SurnameField.TextMarginTop = 0;
            this.SurnameField.TextPlaceholder = "";
            this.SurnameField.UseSystemPasswordChar = false;
            this.SurnameField.WordWrap = true;
            // 
            // DateOfEmploymentLabel
            // 
            this.DateOfEmploymentLabel.AutoSize = true;
            this.DateOfEmploymentLabel.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.DateOfEmploymentLabel.Location = new System.Drawing.Point(2, 138);
            this.DateOfEmploymentLabel.Name = "DateOfEmploymentLabel";
            this.DateOfEmploymentLabel.Size = new System.Drawing.Size(74, 38);
            this.DateOfEmploymentLabel.TabIndex = 79;
            this.DateOfEmploymentLabel.Text = "Дата\r\nприема";
            // 
            // MobPhoneLabel
            // 
            this.MobPhoneLabel.AutoSize = true;
            this.MobPhoneLabel.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.MobPhoneLabel.Location = new System.Drawing.Point(2, 215);
            this.MobPhoneLabel.Name = "MobPhoneLabel";
            this.MobPhoneLabel.Size = new System.Drawing.Size(81, 19);
            this.MobPhoneLabel.TabIndex = 78;
            this.MobPhoneLabel.Text = "Телефон";
            // 
            // AdressLabel
            // 
            this.AdressLabel.AutoSize = true;
            this.AdressLabel.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.AdressLabel.Location = new System.Drawing.Point(2, 183);
            this.AdressLabel.Name = "AdressLabel";
            this.AdressLabel.Size = new System.Drawing.Size(62, 19);
            this.AdressLabel.TabIndex = 77;
            this.AdressLabel.Text = "Адрес";
            // 
            // MiddlenameLabel
            // 
            this.MiddlenameLabel.AutoSize = true;
            this.MiddlenameLabel.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.MiddlenameLabel.Location = new System.Drawing.Point(2, 110);
            this.MiddlenameLabel.Name = "MiddlenameLabel";
            this.MiddlenameLabel.Size = new System.Drawing.Size(86, 19);
            this.MiddlenameLabel.TabIndex = 76;
            this.MiddlenameLabel.Text = "Отчество";
            // 
            // NameLabel
            // 
            this.NameLabel.AutoSize = true;
            this.NameLabel.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.NameLabel.Location = new System.Drawing.Point(2, 77);
            this.NameLabel.Name = "NameLabel";
            this.NameLabel.Size = new System.Drawing.Size(41, 19);
            this.NameLabel.TabIndex = 75;
            this.NameLabel.Text = "Имя";
            // 
            // SurnameLabel
            // 
            this.SurnameLabel.AutoSize = true;
            this.SurnameLabel.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.SurnameLabel.Location = new System.Drawing.Point(2, 42);
            this.SurnameLabel.Name = "SurnameLabel";
            this.SurnameLabel.Size = new System.Drawing.Size(82, 19);
            this.SurnameLabel.TabIndex = 74;
            this.SurnameLabel.Text = "Фамилия";
            // 
            // PositionDropdown
            // 
            this.PositionDropdown.BackColor = System.Drawing.Color.White;
            this.PositionDropdown.BackgroundColor = System.Drawing.Color.White;
            this.PositionDropdown.BorderColor = System.Drawing.Color.Black;
            this.PositionDropdown.BorderRadius = 2;
            this.PositionDropdown.Color = System.Drawing.Color.Black;
            this.PositionDropdown.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.PositionDropdown.DisabledBackColor = System.Drawing.Color.Gray;
            this.PositionDropdown.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PositionDropdown.DisabledColor = System.Drawing.Color.Gray;
            this.PositionDropdown.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.PositionDropdown.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.PositionDropdown.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.PositionDropdown.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thick;
            this.PositionDropdown.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.PositionDropdown.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.PositionDropdown.FillDropDown = false;
            this.PositionDropdown.FillIndicator = false;
            this.PositionDropdown.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.PositionDropdown.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.PositionDropdown.ForeColor = System.Drawing.Color.Black;
            this.PositionDropdown.FormattingEnabled = true;
            this.PositionDropdown.Icon = null;
            this.PositionDropdown.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.PositionDropdown.IndicatorColor = System.Drawing.Color.FromArgb(((int)(((byte)(107)))), ((int)(((byte)(107)))), ((int)(((byte)(107)))));
            this.PositionDropdown.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.PositionDropdown.ItemBackColor = System.Drawing.Color.White;
            this.PositionDropdown.ItemBorderColor = System.Drawing.Color.White;
            this.PositionDropdown.ItemForeColor = System.Drawing.Color.Black;
            this.PositionDropdown.ItemHeight = 35;
            this.PositionDropdown.ItemHighLightColor = System.Drawing.Color.Thistle;
            this.PositionDropdown.ItemHighLightForeColor = System.Drawing.Color.White;
            this.PositionDropdown.ItemTopMargin = 3;
            this.PositionDropdown.Location = new System.Drawing.Point(99, 353);
            this.PositionDropdown.MaximumSize = new System.Drawing.Size(500, 0);
            this.PositionDropdown.MaxLength = 3255;
            this.PositionDropdown.MinimumSize = new System.Drawing.Size(200, 0);
            this.PositionDropdown.Name = "PositionDropdown";
            this.PositionDropdown.Size = new System.Drawing.Size(209, 41);
            this.PositionDropdown.TabIndex = 89;
            this.PositionDropdown.Text = "Выбрать";
            this.PositionDropdown.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.PositionDropdown.TextLeftMargin = 5;
            // 
            // HiringStatusDropdown
            // 
            this.HiringStatusDropdown.BackColor = System.Drawing.Color.White;
            this.HiringStatusDropdown.BackgroundColor = System.Drawing.Color.White;
            this.HiringStatusDropdown.BorderColor = System.Drawing.Color.Black;
            this.HiringStatusDropdown.BorderRadius = 2;
            this.HiringStatusDropdown.Color = System.Drawing.Color.Black;
            this.HiringStatusDropdown.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.HiringStatusDropdown.DisabledBackColor = System.Drawing.Color.Gray;
            this.HiringStatusDropdown.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.HiringStatusDropdown.DisabledColor = System.Drawing.Color.Gray;
            this.HiringStatusDropdown.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.HiringStatusDropdown.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.HiringStatusDropdown.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.HiringStatusDropdown.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thick;
            this.HiringStatusDropdown.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.HiringStatusDropdown.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.HiringStatusDropdown.FillDropDown = false;
            this.HiringStatusDropdown.FillIndicator = false;
            this.HiringStatusDropdown.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.HiringStatusDropdown.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.HiringStatusDropdown.ForeColor = System.Drawing.Color.Black;
            this.HiringStatusDropdown.FormattingEnabled = true;
            this.HiringStatusDropdown.Icon = null;
            this.HiringStatusDropdown.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.HiringStatusDropdown.IndicatorColor = System.Drawing.Color.FromArgb(((int)(((byte)(107)))), ((int)(((byte)(107)))), ((int)(((byte)(107)))));
            this.HiringStatusDropdown.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.HiringStatusDropdown.ItemBackColor = System.Drawing.Color.White;
            this.HiringStatusDropdown.ItemBorderColor = System.Drawing.Color.White;
            this.HiringStatusDropdown.ItemForeColor = System.Drawing.Color.Black;
            this.HiringStatusDropdown.ItemHeight = 35;
            this.HiringStatusDropdown.ItemHighLightColor = System.Drawing.Color.Thistle;
            this.HiringStatusDropdown.ItemHighLightForeColor = System.Drawing.Color.White;
            this.HiringStatusDropdown.ItemTopMargin = 3;
            this.HiringStatusDropdown.Location = new System.Drawing.Point(99, 311);
            this.HiringStatusDropdown.MaximumSize = new System.Drawing.Size(500, 0);
            this.HiringStatusDropdown.MaxLength = 3255;
            this.HiringStatusDropdown.MinimumSize = new System.Drawing.Size(200, 0);
            this.HiringStatusDropdown.Name = "HiringStatusDropdown";
            this.HiringStatusDropdown.Size = new System.Drawing.Size(209, 41);
            this.HiringStatusDropdown.TabIndex = 88;
            this.HiringStatusDropdown.Text = "Выбрать";
            this.HiringStatusDropdown.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.HiringStatusDropdown.TextLeftMargin = 5;
            // 
            // StaffAdd
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(311, 451);
            this.Controls.Add(this.PositionDropdown);
            this.Controls.Add(this.HiringStatusDropdown);
            this.Controls.Add(this.DatePicker);
            this.Controls.Add(this.PositionLabel);
            this.Controls.Add(this.HeaderLabel);
            this.Controls.Add(this.HiringStatusLabel);
            this.Controls.Add(this.EmailField);
            this.Controls.Add(this.EmailLabel);
            this.Controls.Add(this.PassportField);
            this.Controls.Add(this.PassportLabel);
            this.Controls.Add(this.AdressField);
            this.Controls.Add(this.MobPhoneField);
            this.Controls.Add(this.MiddlenameField);
            this.Controls.Add(this.NameField);
            this.Controls.Add(this.SurnameField);
            this.Controls.Add(this.DateOfEmploymentLabel);
            this.Controls.Add(this.MobPhoneLabel);
            this.Controls.Add(this.AdressLabel);
            this.Controls.Add(this.MiddlenameLabel);
            this.Controls.Add(this.NameLabel);
            this.Controls.Add(this.SurnameLabel);
            this.Controls.Add(this.ButtonCancel);
            this.Controls.Add(this.AddButton);
            this.DoubleBuffered = true;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "StaffAdd";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "SotrudAdd";
            this.Load += new System.EventHandler(this.StaffAdd_Load);
            this.Shown += new System.EventHandler(this.StaffAdd_Shown);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.Framework.UI.BunifuCustomLabel HeaderLabel;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton ButtonCancel;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton AddButton;
        public Bunifu.UI.WinForms.BunifuDatePicker DatePicker;
        public Bunifu.Framework.UI.BunifuCustomLabel PositionLabel;
        public Bunifu.Framework.UI.BunifuCustomLabel HiringStatusLabel;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox EmailField;
        public Bunifu.Framework.UI.BunifuCustomLabel EmailLabel;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox PassportField;
        public Bunifu.Framework.UI.BunifuCustomLabel PassportLabel;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox AdressField;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox MobPhoneField;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox MiddlenameField;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox NameField;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox SurnameField;
        public Bunifu.Framework.UI.BunifuCustomLabel DateOfEmploymentLabel;
        public Bunifu.Framework.UI.BunifuCustomLabel MobPhoneLabel;
        public Bunifu.Framework.UI.BunifuCustomLabel AdressLabel;
        public Bunifu.Framework.UI.BunifuCustomLabel MiddlenameLabel;
        public Bunifu.Framework.UI.BunifuCustomLabel NameLabel;
        public Bunifu.Framework.UI.BunifuCustomLabel SurnameLabel;
        public Bunifu.UI.WinForms.BunifuDropdown PositionDropdown;
        public Bunifu.UI.WinForms.BunifuDropdown HiringStatusDropdown;
    }
}